-- Rename all columns

ALTER TABLE telco_general_table
RENAME COLUMN `Customer ID` TO customer_id,
RENAME COLUMN `Gender` TO gender,
RENAME COLUMN `Age` TO age,
RENAME COLUMN `Under 30` TO under_30,
RENAME COLUMN `Senior Citizen` TO senior_citizen,
RENAME COLUMN `Married` TO married,
RENAME COLUMN `Dependents` TO dependents,
RENAME COLUMN `Number of Dependents` TO number_of_dependents,
RENAME COLUMN `Country` TO country,
RENAME COLUMN `State` TO state,
RENAME COLUMN `City` TO city,
RENAME COLUMN `Zip Code` TO zip_code,
RENAME COLUMN `Latitude` TO latitude,
RENAME COLUMN `Longitude` TO longitude,
RENAME COLUMN `Quarter` TO quarter,
RENAME COLUMN `Referred a Friend` TO referred_a_friend,
RENAME COLUMN `Number of Referrals` TO number_of_referrals,
RENAME COLUMN `Tenure in Months` TO tenure_in_months,
RENAME COLUMN `Offer` TO offer,
RENAME COLUMN `Phone Service` TO phone_service,
RENAME COLUMN `Avg Monthly Long Distance Charges` TO avg_monthly_long_distance_charges,
RENAME COLUMN `Multiple Lines` TO multiple_lines,
RENAME COLUMN `Internet Service` TO internet_service,
RENAME COLUMN `Internet Type` TO internet_type,
RENAME COLUMN `Avg Monthly GB Download` TO avg_monthly_gb_download,
RENAME COLUMN `Online Security` TO online_security,
RENAME COLUMN `Online Backup` TO online_backup,
RENAME COLUMN `Device Protection Plan` TO device_protection_plan,
RENAME COLUMN `Premium Tech Support` TO premium_tech_support,
RENAME COLUMN `Streaming TV` TO streaming_tv,
RENAME COLUMN `Streaming Movies` TO streaming_movies,
RENAME COLUMN `Streaming Music` TO streaming_music,
RENAME COLUMN `Unlimited Data` TO unlimited_data,
RENAME COLUMN `Contract` TO contract,
RENAME COLUMN `Paperless Billing` TO paperless_billing,
RENAME COLUMN `Payment Method` TO payment_method,
RENAME COLUMN `Monthly Charge` TO monthly_charge,
RENAME COLUMN `Total Charges` TO total_charges,
RENAME COLUMN `Total Refunds` TO total_refunds,
RENAME COLUMN `Total Extra Data Charges` TO total_extra_data_charges,
RENAME COLUMN `Total Long Distance Charges` TO total_long_distance_charges,
RENAME COLUMN `Total Revenue` TO total_revenue,
RENAME COLUMN `Customer Status` TO customer_status,
RENAME COLUMN `Churn Label` TO churn_label,
RENAME COLUMN `Churn Value` TO churn_value,
RENAME COLUMN `Churn Category` TO churn_category,
RENAME COLUMN `Churn Reason` TO churn_reason;